CREATE TABLE CLIENTES_PEL(
ID_CLIENTE VARCHAR2(40) NOT NULL,
NOMBRE VARCHAR2(15) NOT NULL,
APELL_PAT VARCHAR2(15) NOT NULL,
APELL_MAT VARCHAR2(15) ,
TELEFONO VARCHAR2(15) NOT NULL,
CONSTRAINT PK_CLIENTES PRIMARY KEY(ID_CLIENTE)
);

CREATE  TABLE PELICULAS(
  CODIGO VARCHAR2(20)        NOT NULL,
  TITULO VARCHAR2(40)        NOT NULL,
  DIRECTOR VARCHAR2(30)       NOT NULL,
  ACTOR_PRINCIPAL VARCHAR2(20) NOT NULL,
  GENERO VARCHAR2(20)      NOT NULL,
  PRECIO FLOAT              NOT NULL,
 
  CONSTRAINT PK_PELICULAS PRIMARY KEY(CODIGO)
);


CREATE TABLE COMPRA(
ID_COMPRA VARCHAR2(10) NOT NULL,
ID_CLIENTE VARCHAR2(40) NOT NULL,
CONSTRAINT PK_COMPRA PRIMARY KEY(ID_COMPRA),
CONSTRAINT FK_IDCLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES_PEL(ID_CLIENTE)
);

CREATE TABLE DETALLE_COMPRA(
ID_DETALLE VARCHAR2(10) NOT NULL,
ID_COMPRA VARCHAR2(10) NOT NULL,
CODIGO VARCHAR2(20)   NOT NULL,
CANTIDAD INTEGER NOT NULL,
SUBTOTAL FLOAT NOT NULL,
TOTAL FLOAT NOT NULL,
CONSTRAINT PK_DETALLE PRIMARY KEY (ID_DETALLE),
CONSTRAINT FK_IDCOMPRA FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(ID_COMPRA),
CONSTRAINT FK_CODIGO FOREIGN KEY(CODIGO) REFERENCES PELICULAS(CODIGO)
);

drop table COMPRA;
drop table DETALLE_COMPRA;
drop table CLIENTEs_PEL;
commit;
